# Generated by Django 3.0.3 on 2020-02-05 03:42

from django.db import migrations

def create_data(apps, schema_editor):
    Candidate = apps.get_model('Candidates', 'Candidate')
    Candidate(first_name="Candidate 001", last_name="Candidate 001", email="Candidate001@email.com", phone="00000000", address="Candidate 000 Address", description= "Candidate 001 description").save()

class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_info', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
