# Generated by Django 3.0.3 on 2020-02-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_info', '0002_recruiter_info'),
    ]

    operations = [
    ]
