# Generated by Django 3.0.3 on 2020-02-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_info', '0003_recruiter_info'),
    ]

    operations = [
    ]
